services:
  mewo-portal:
    container_name: mewo-portal
    restart: unless-stopped
    build: .
    ports:
      - "8082:8082"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`mewo.gay`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=8082"

networks:
  traefik:
    name: traefik
    external: true
